name: Sync Fork with Upstream

on:
  # Schedule the workflow to run every day at midnight
  schedule:
    - cron: '0 0 * * *'
  # Allows manual trigger from the GitHub Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.0.0.b
        with:
          # The URL of the original (upstream) public repo you forked from
          upstream_repo: "https://github.com/Jaz0XD/Tux_Glug_meeting_event-documentation.git"
          # The branch in your fork to sync
          target_branch: main 
          # The branch in the upstream repo to sync from
          upstream_branch: main
          # GitHub Bot token for authentication
          token: ${{ secrets.GITHUB_TOKEN }}
